spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fire?useUnicode=true&characterEncoding=utf8
    username: root
    password: root12345
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
  context-path: /thridParty