spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fire?useUnicode=true&characterEncoding=utf8s
    username: root
    password: Fire@gyky408..
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 6001
  context-path: /thridParty